services:
  backend:
    build:
      args:
      - NODE_ENV=development
      - PORT=8080
      context: backend
      target: development
    command: npm run start-watch
    env_file: ./.env
    environment:
      - DB_NAME=marketplace
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - NODE_ENV=development 
    ports:
      - 8080:8080
      - 9229:9229
      - 9230:9230
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
    depends_on:
      db:
        condition: service_healthy
       
  db:
    image: mysql:8.0.27
    container_name: db 
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", -p$$MYSQL_ROOT_PASSWORD, "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 30s
    
  frontend:
    build:
      args:
      - PORT=3000
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/vite.config.js:/code/vite.config.js
      - ./frontend/src:/code/src
    depends_on:
      - backend
volumes:
   db-data:
