services:
  backend:
    build:
      args:
      - NODE_ENV=development
      - PORT=8080
      context: backend
      target: development
    command: npm run start-watch
    env_file: ./.env
    environment:
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - NODE_ENV=development
    ports:
      - 8080:8080
      - 9229:9229
      - 9230:9230
    volumes:
      - ./backend/src:/code/backend/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD_FILE=$DB_PASSWORD
  frontend:
    build:
      args:
      - PORT=3000
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/node_modules:/usr/frontend/node_modules
      - ./frontend/vite.config.js:/usr/frontend/vite.config.js
      - ./frontend/src:/code/frontend/src
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
